In [ ]:
import pandas as pd

In [ ]:
melbourne_file_path = 'https://raw.githubusercontent.com/dipalira/Melbourne-Housing-Data-Kaggle/refs/heads/master/Data/Melbourne_housing_FULL.csv'

In [ ]:
melbourne_data = pd.read_csv(melbourne_file_path)

In [ ]:
melbourne_data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [ ]:
melbourne_data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [ ]:
melbourne_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,34857.000000,2.724700e+04,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,15551.000000,26881.000000,26881.000000,34854.000000
mean,3.031012,1.050173e+06,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,160.25640,1965.289885,-37.810634,145.001851,7572.888306
std,0.969933,6.414671e+05,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,401.26706,37.328178,0.090279,0.120169,4428.090313
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.350000e+05,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,102.00000,1940.000000,-37.862950,144.933500,4385.000000
50%,3.000000,8.700000e+05,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.00000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.295000e+06,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,188.00000,2000.000000,-37.754100,145.071900,10412.000000
max,16.000000,1.120000e+07,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.00000,2106.000000,-37.390200,145.526350,21650.000000

In [ ]:
melbourne_data = melbourne_data.dropna(axis = 0)

In [ ]:
melbourne_data

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra City Council,-37.80720,144.99410,Northern Metropolitan,4019.0
11,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,2.0,0.0,245.0,210.0,1910.0,Yarra City Council,-37.80240,144.99930,Northern Metropolitan,4019.0
14,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,...,1.0,2.0,256.0,107.0,1890.0,Yarra City Council,-37.80600,144.99540,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34847,Wollert,27 Birchmore Rd,3,h,500000.0,PI,Ray,24/02/2018,25.5,3750.0,...,2.0,2.0,383.0,118.0,2016.0,Whittlesea City Council,-37.61940,145.03951,Northern Metropolitan,2940.0
34849,Wollert,35 Kingscote Wy,3,h,570000.0,SP,RW,24/02/2018,25.5,3750.0,...,2.0,2.0,404.0,158.0,2012.0,Whittlesea City Council,-37.61031,145.03393,Northern Metropolitan,2940.0
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [ ]:
melbourne_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,8887.000000,8.887000e+03,8887.000000,8887.000000,8887.000000,8887.000000,8887.000000,8887.000000,8887.000000,8887.000000,8887.000000,8887.000000,8887.000000
mean,3.098909,1.092902e+06,11.199887,3111.662653,3.078204,1.646450,1.692247,523.480365,149.309477,1965.753348,-37.804501,144.991393,7475.940137
std,0.963786,6.793819e+05,6.813402,112.614268,0.966269,0.721611,0.975464,1061.324228,87.925580,37.040876,0.090549,0.118919,4375.024364
min,1.000000,1.310000e+05,0.000000,3000.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1196.000000,-38.174360,144.423790,249.000000
25%,2.000000,6.410000e+05,6.400000,3044.000000,2.000000,1.000000,1.000000,212.000000,100.000000,1945.000000,-37.858560,144.920000,4382.500000
50%,3.000000,9.000000e+05,10.200000,3084.000000,3.000000,2.000000,2.000000,478.000000,132.000000,1970.000000,-37.798700,144.998500,6567.000000
75%,4.000000,1.345000e+06,13.900000,3150.000000,4.000000,2.000000,2.000000,652.000000,180.000000,2000.000000,-37.748945,145.064560,10331.000000
max,12.000000,9.000000e+06,47.400000,3977.000000,12.000000,9.000000,10.000000,42800.000000,3112.000000,2019.000000,-37.407200,145.526350,21650.000000

# Prediction Target (y)

In [ ]:
y = melbourne_data.Price

In [ ]:
y

2        1035000.0
4        1465000.0
6        1600000.0
11       1876000.0
14       1636000.0
           ...
34847     500000.0
34849     570000.0
34853     888000.0
34854     705000.0
34856    1020000.0
Name: Price, Length: 8887, dtype: float64

# Choose Features (X)

In [ ]:
melbourne_data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [ ]:
melbourne_features = ['Rooms','Bathroom', 'Landsize', 'Lattitude', 'Longtitude']
X = melbourne_data[melbourne_features]

In [ ]:
X

       Rooms  Bathroom  Landsize  Lattitude  Longtitude
2          2       1.0     156.0  -37.80790   144.99340
4          3       2.0     134.0  -37.80930   144.99440
6          4       1.0     120.0  -37.80720   144.99410
11         3       2.0     245.0  -37.80240   144.99930
14         2       1.0     256.0  -37.80600   144.99540
...      ...       ...       ...        ...         ...
34847      3       2.0     383.0  -37.61940   145.03951
34849      3       2.0     404.0  -37.61031   145.03393
34853      2       2.0      98.0  -37.81551   144.88826
34854      2       1.0     220.0  -37.82286   144.87856
34856      2       1.0     250.0  -37.81810   144.89351

[8887 rows x 5 columns]

In [ ]:
from sklearn.tree import DecisionTreeRegressor
melbourne_model = DecisionTreeRegressor(random_state = 1)
#Fit the model to our current data
melbourne_model.fit(X,y)

DecisionTreeRegressor(random_state=1)

In [ ]:
print(X.head())

    Rooms  Bathroom  Landsize  Lattitude  Longtitude
2       2       1.0     156.0   -37.8079    144.9934
4       3       2.0     134.0   -37.8093    144.9944
6       4       1.0     120.0   -37.8072    144.9941
11      3       2.0     245.0   -37.8024    144.9993
14      2       1.0     256.0   -37.8060    144.9954

In [ ]:
melbourne_model.predict(X.head())

array([1035000., 1465000., 1600000., 1876000., 1636000.])

In [ ]:
# d = {'Rooms': [15], 'Bathroom':[10],  'Landsize': [1000],  'Lattitude': [-37.8079],  'Longtitude': [144.9934]}
# df = pd.DataFrame(d)

In [ ]:
# melbourne_model.predict(df)

# Model Validation
Mean Absolute Error (MAE) metric

In [ ]:
from sklearn.metrics import mean_absolute_error
predicted_home_prices = melbourne_model.predict(X)
mean_absolute_error(y,predicted_home_prices)

897.2844229398746

In [ ]:
from sklearn.model_selection import train_test_split
train_X, val_X, train_y, val_y = train_test_split(X,y, random_state= 1)

In [ ]:
a, b, c = (1, 3, 4)
print(b)

3

In [ ]:
melbourne_model = DecisionTreeRegressor()
melbourne_model.fit(train_X, train_y)

DecisionTreeRegressor()

In [ ]:
incorrect_prediction = melbourne_model.predict(train_X)
print(mean_absolute_error(train_y, incorrect_prediction))

389.6224056014003

In [ ]:
train_X

       Rooms  Bathroom  Landsize  Lattitude  Longtitude
27414      2       1.0     670.0  -37.89490   144.66260
4075       4       2.0       0.0  -37.74650   144.91000
7886       1       1.0       0.0  -37.84360   144.94400
10252      1       1.0       0.0  -37.76200   144.99600
31000      4       1.0     583.0  -37.71357   144.57512
...      ...       ...       ...        ...         ...
13554      4       3.0     697.0  -37.70100   144.99930
30441      3       1.0     593.0  -37.94406   145.03219
15315      3       2.0     600.0  -37.57686   144.71023
9873       5       2.0     661.0  -37.76510   144.82410
8273       3       1.0     495.0  -37.75210   145.01140

[6665 rows x 5 columns]

In [ ]:
incorrect_prediction

array([ 547000., 1170000.,  470000., ...,  410000.,  605000.,  890000.])

In [ ]:
val_prediction = melbourne_model.predict(val_X)

In [ ]:
print(mean_absolute_error(val_y, val_prediction))

252417.40774077407

In [ ]:
def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
  model = DecisionTreeRegressor(max_leaf_nodes = max_leaf_nodes, random_state = 0)
  model.fit(train_X, train_y)
  preds_val = model.predict(val_X)
  mae = mean_absolute_error(val_y, preds_val)
  return mae
for max_leaf_nodes in [2, 10, 20, 30, 40, 50, 100, 200, 250, 300, 350, 400]:
  my_mae = get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
  print(f"Maximum leaf nodes = {max_leaf_nodes}, Error = {my_mae}")

Maximum leaf nodes = 2, Error = 434051.3222339987
Maximum leaf nodes = 10, Error = 320323.11545654776
Maximum leaf nodes = 20, Error = 295217.9557555797
Maximum leaf nodes = 30, Error = 281668.50305117166
Maximum leaf nodes = 40, Error = 268140.13802793896
Maximum leaf nodes = 50, Error = 269635.77944333066
Maximum leaf nodes = 100, Error = 251472.71131411262
Maximum leaf nodes = 200, Error = 237595.34453951268
Maximum leaf nodes = 250, Error = 234448.9314130733
Maximum leaf nodes = 300, Error = 235189.23487943437
Maximum leaf nodes = 350, Error = 234224.26692657016
Maximum leaf nodes = 400, Error = 234074.74251054192

# Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import median_absolute_error

forest_model  = RandomForestRegressor(n_estimators = 50, random_state = 1)
forest_model.fit(train_X, train_y)
melb_preds = forest_model.predict(val_X)
print(mean_absolute_error(val_y, melb_preds))

187915.7592919292

In [ ]:
melbourne_data.Suburb.unique()

array(['Abbotsford', 'Airport West', 'Albert Park', 'Alphington',
       'Altona', 'Altona North', 'Armadale', 'Ascot Vale', 'Ashburton',
       'Ashwood', 'Avondale Heights', 'Balaclava', 'Balwyn',
       'Balwyn North', 'Bentleigh', 'Bentleigh East', 'Box Hill',
       'Braybrook', 'Brighton', 'Brighton East', 'Brunswick',
       'Brunswick West', 'Bulleen', 'Burwood', 'Camberwell', 'Canterbury',
       'Carlton North', 'Carnegie', 'Caulfield', 'Caulfield North',
       'Caulfield South', 'Chadstone', 'Clifton Hill', 'Coburg',
       'Coburg North', 'Collingwood', 'Doncaster', 'Eaglemont',
       'Elsternwick', 'Elwood', 'Essendon', 'Essendon North', 'Fairfield',
       'Fitzroy', 'Fitzroy North', 'Flemington', 'Footscray', 'Glen Iris',
       'Glenroy', 'Gowanbrae', 'Hadfield', 'Hampton', 'Hampton East',
       'Hawthorn', 'Heidelberg Heights', 'Heidelberg West', 'Hughesdale',
       'Ivanhoe', 'Kealba', 'Keilor East', 'Kensington', 'Kew',
       'Kew East', 'Maidstone', 'Malvern', 'Malvern East', 'Maribyrnong',
       'Melbourne', 'Middle Park', 'Mont Albert', 'Moonee Ponds',
       'Moorabbin', 'Newport', 'Niddrie', 'North Melbourne', 'Northcote',
       'Oak Park', 'Oakleigh South', 'Parkville', 'Pascoe Vale',
       'Port Melbourne', 'Prahran', 'Preston', 'Reservoir', 'Richmond',
       'Rosanna', 'Seddon', 'South Melbourne', 'South Yarra', 'Southbank',
       'Spotswood', 'St Kilda', 'Strathmore', 'Sunshine',
       'Sunshine North', 'Sunshine West', 'Surrey Hills',
       'Templestowe Lower', 'Thornbury', 'Toorak', 'Viewbank', 'Watsonia',
       'West Melbourne', 'Williamstown', 'Williamstown North', 'Windsor',
       'Yallambie', 'Yarraville', 'Aberfeldie', 'Bellfield',
       'Brunswick East', 'Burnley', 'Carlton', 'East Melbourne',
       'Essendon West', 'Fawkner', 'Hawthorn East', 'Heidelberg',
       'Ivanhoe East', 'Jacana', 'Kingsbury', 'Kingsville', 'Murrumbeena',
       'Ormond', 'West Footscray', 'Albion', 'Brooklyn', 'Glen Huntly',
       'Oakleigh', 'Ripponlea', 'Cremorne', 'South Kingsville',
       'Strathmore Heights', 'Travancore', 'Caulfield East', 'Seaholme',
       'Keilor Park', 'Gardenvale', 'Princes Hill', 'Bayswater',
       'Briar Hill', 'Broadmeadows', 'Burnside Heights', 'Cairnlea',
       'Cheltenham', 'Craigieburn', 'Croydon', 'Dandenong North',
       'Diamond Creek', 'Doncaster East', 'Donvale', 'Doreen', 'Eltham',
       'Epping', 'Frankston North', 'Frankston South', 'Gisborne',
       'Greensborough', 'Healesville', 'Highett', 'Hillside',
       'Huntingdale', 'Keilor Downs', 'Keysborough', 'Kings Park',
       'Lalor', 'Melton', 'Mernda', 'Mill Park', 'Mitcham', 'Montmorency',
       'Mount Waverley', 'Nunawading', 'Parkdale', 'Point Cook',
       'Rowville', 'Sandringham', 'Seaford', 'South Morang', 'Springvale',
       'St Albans', 'Sunbury', 'Tarneit', 'Taylors Hill', 'Werribee',
       'Wyndham Vale', 'Beaumaris', 'Blackburn', 'Bonbeach', 'Boronia',
       'Burwood East', 'Caroline Springs', 'Carrum', 'Chelsea', 'Clayton',
       'Dandenong', 'Dingley Village', 'Doveton', 'Frankston',
       'Glen Waverley', 'Greenvale', 'Heathmont', 'Hoppers Crossing',
       'Melton South', 'Melton West', 'Mentone', 'Mooroolbark',
       'Mordialloc', 'Oakleigh East', 'Ringwood East', 'Roxburgh Park',
       'Seabrook', 'Templestowe', 'Thomastown', 'Vermont',
       'Watsonia North', 'Westmeadows', 'Wheelers Hill',
       'Bayswater North', 'Berwick', 'Black Rock', 'Blackburn North',
       'Bundoora', 'Carrum Downs', 'Croydon North', 'Ferntree Gully',
       'Gladstone Park', 'Hallam', 'Mulgrave', 'Notting Hill',
       'Ringwood North', 'Skye', 'Sydenham', 'Taylors Lakes',
       'Vermont South', 'Beaconsfield Upper', 'Blackburn South',
       'Chelsea Heights', 'Eltham North', 'Meadow Heights',
       'Mount Evelyn', 'Noble Park', 'North Warrandyte', 'Riddells Creek',
       'Sandhurst', 'Wantirna South', 'Chirnside Park', 'Croydon Hills',
       'Derrimut', 'Edithvale', 'Forest Hill', 'Keilor', 'Knoxfield',
       'Lower Plenty', 'St Helena', 'Truganina', 'Tullamarine', 'Wollert',
       'Deer Park', 'Hampton Park', 'Montrose', 'Ringwood', 'The Basin',
       'Altona Meadows', 'Clarinda', 'Deepdene', 'Delahey',
       'Diggers Rest', 'Hurstbridge', 'Kurunjang', 'McKinnon', 'Scoresby',
       'Aspendale', 'Endeavour Hills', 'Narre Warren', 'Pakenham',
       'Warrandyte', 'Beaconsfield', 'Langwarrin', 'Springvale South',
       'Yarra Glen', 'Albanvale', 'Ardeer', 'Brookfield',
       'Cranbourne North', 'Emerald', 'Whittlesea', 'Clayton South',
       'Coolaroo', 'Dallas', 'Wantirna', 'Waterways', 'Wallan',
       'Williams Landing', 'Campbellfield', 'Kilsyth', 'Plumpton',
       'Burnside', 'Cranbourne', 'Kooyong', 'Bacchus Marsh', 'Attwood',
       'Croydon South', 'Botanic Ridge', 'Gisborne South', 'Wattle Glen',
       'Aspendale Gardens', 'Mickleham', 'Officer', 'Upwey',
       'Lysterfield', 'Patterson Lakes', 'Bullengarook', 'Keilor Lodge',
       'Research'], dtype=object)

In [ ]:
data = pd.read_csv(melbourne_file_path)
data = data.dropna(subset = ['Price'])